name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  url_launcher: ^5.0.3
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  fonts:
    - family: Mission Script
      fonts:
        - asset: fonts/Mission-Script.otf
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

  uses-material-design: true

  assets:
    - images/
